# Generated by Django 5.0.6 on 2024-07-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.URLField(blank=True, null=True)),
                ('product_url', models.URLField(unique=True)),
                ('rating', models.CharField(blank=True, max_length=10, null=True)),
                ('price', models.CharField(blank=True, max_length=20, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('dominant_color', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
