# Generated by Django 5.0.6 on 2024-07-05 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searcher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('img_url', models.URLField(blank=True, null=True)),
                ('price', models.CharField(blank=True, max_length=20, null=True)),
                ('reviews', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
